### ISSUE TITLE
tiny start error :[core-task]: npm run watch 命令执行行失败

### ISSUE THREAD

**Issue by xingyewuyu** [opentiny/tiny-vue#1540]
初始化项目时，选择tiny init dev , 再输入tiny-toolkit-mytest 然后显示如下成功信息：
![image](https://github.com/opentiny/tiny-vue/assets/33115396/fde5795d-8957-4ce3-9ec6-64d2ba8fe928)
接着运行tiny start后，出现如下错误：
E:\biancheng\tiny_project_test\node_modules\.store\append-transform@1.0.0\node_modules\append-transform\index.js:1
TypeError [ERR_INVALID_ARG_TYPE]: The "mod" argument must be an instance of Module. Received an instance of Module
    at makeRequireFunction (node:internal/modules/helpers:134:11)
    at Module._compile (node:internal/modules/cjs/loader:1358:19)
    at Module.replacementCompile (E:\biancheng\tiny_project_test\node_modules\.store\append-transform@1.0.0\node_modules\append-transform\index.js:58:13)
    at Generator.next (<anonymous>)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at E:\biancheng\tiny_project_test\node_modules\.store\append-transform@1.0.0\node_modules\append-transform\index.js:62:4
    at Object.<anonymous> (E:\biancheng\tiny_project_test\node_modules\.store\append-transform@1.0.0\node_modules\append-transform\index.js:62:4) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.12.1
ERROR: "test:unit -- --watch" exited with 1.
2024-04-08 20:27:33 [core-task]: npm run watch 命令执行行失败

**Comment by xingyewuyu** [comment]
![image](https://github.com/opentiny/tiny-vue/assets/33115396/4750474e-9451-4ac5-8471-17f02dae8d39)
shang'm 输入tiny start 后， 出现上面的错误，不知道如何解决？

**Comment by shenjunjian** [comment]
属于 Tiny Cli的问题， 它的仓库地址为： https://github.com/opentiny/tiny-cli/issues  
请将该问题转到那里
